name: Birthday
version: ${project.version}
main: me.tererun.plugin.birthday.birthday.Birthday
api-version: 1.18
authors: [ tererun ]
description: Birthday
commands:
  birthday:
    description: birthday